mongo:
  address: "mongodb://localhost:27017"
  database: "scrapping"

crawler:
  allow-url-revisit: false
  allowed-domains:
  #  - www.google.com
  async: true
  detect-charset: false
  disallowed-domains:
  #  - www.google.com
  ignore-robots-txt: false

  limit:
    delay: 0
    domain-regexp: ""
    domain-glob: "*"
    random-delay: 0
    parallelism: 0 # 0 = will take the max os cpu number

  max-body-size: 10485760 # 10MB (10 * 1024 * 1024 bytes)
  max-depth: 0
  max-url-visited: 100
  random-users-agents: false
  sleep-between-request: 0

  # see http://go-colly.org/docs/best_practices/storage/ for more infos
  storage:
    clear-on-start: false
    redis:
      address:  "127.0.0.1:6379"
      password: ""
      db:       0
      prefix:   ""
  #  mongodb:
  #    Database: "pulse"
  #    Uri: "mongodb://127.0.0.1:27017"

  user-agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.0129.115 Safari/537.36"